SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping constraints from [dbo].[States]'
GO
ALTER TABLE [dbo].[States] DROP CONSTRAINT [PK_States]
GO
PRINT N'Dropping [dbo].[States]'
GO
DROP TABLE [dbo].[States]
GO

