SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[GetAllWidgets]'
GO

ALTER   PROCEDURE [dbo].[GetAllWidgets]
AS
BEGIN
	SELECT w.RecordID,
           w.Description,
		   p.Price
	FROM Widgets w INNER JOIN dbo.WidgetPrices p ON p.RecordID = w.RecordID
END
GO

