# This is a basic workflow to help you get started with Actions intended for Flyway Teams workflow
 
name: GitHub-Flyway-AutoPilot-Pipeline-Windows

on:
  # Triggers the workflow on push or pull request events but only for the "release" branch
  #push:
    #branches:
      #- release
      #- 'migrations/**'
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
 
  # Enable this for additional debug logging
  ACTIONS_RUNNER_DEBUG: false

  #Repository Secret - Create this within the Projects Settings > Secrets > Actions section
  # Personal Access Tokens (PATs) are the recommended method of authorizing Flyway during a non-interactive session
  # Details on how to do this can be found here: https://documentation.red-gate.com/flyway/flyway-cli-and-api/tutorials/tutorial-personal-access-tokens
  FLYWAY_EMAIL: "${{ secrets.FLYWAY_EMAIL }}" # Enter the email address linked to the Redgate Account that created the PAT
  FLYWAY_TOKEN: "${{ secrets.FLYWAY_TOKEN }}" # Enter the PAT Value (This should be treated like a password and thus as a secure variable.
  # FLYWAY_LICENSE_KEY: "${{ secrets.FLYWAY_LICENSE_KEY }}" # Deprecated Authentication Method. Consider using the new PAT method above for added security.

  BASELINE_VERSION: "001" # This should match the version number of your baseline script
  FIRST_UNDO_SCRIPT: "002" # This should match the first undo version in your project

  # Optional - For ephemeral agents/runners, it's necessary to validate Flyway is installed on each run. Set the below to true to enable the functionality
  FLYWAY_CLI_INSTALL_CHECK: "false" # Setting to false will skip the Flyway CLI check step
  FLYWAY_VERSION: "10.20.1" # This outlines the version of Flyway CLI that will be downloaded if no Flyway CLI is detected on the target agent
  FLYWAY_INSTALL_DIRECTORY: "C:\\FlywayCLI\\" # The path on the agent machine where Flyway CLI will be installed  

  # Optional: Side Task #1 - Setup Flyway Pipeline Integration - https://flyway.red-gate.com/ For More Details
  FLYWAY_PUBLISH_RESULT: "false" # Set this value to true to enable Flyway Pipelines and track your releases centrally!
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Deploy Build
    # The type of runner that the job will run on
    runs-on: "self-hosted" # Options - self-hosted/ubuntu-latest/windows-latest (See here for more details on GitHub hosted runners - https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners)
    environment: 'build' #Ensure this environment name is setup in the projects Settings>Environment area. Ensuring any reviewers are also configFilesured 
    env:
      stage: 'Build'
      
      # Environment Secrets - In a Production setup, Ensure all of the below have been created as an Environment Secret (Projects Settings > Secrets > Actions section, specially related to the environment in question) #
      DATABASE_NAME: "AutoPilotBuild"
      ENVIRONMENT: "Build" # This variable refers to the environment name present in the Flyway Projects TOML file. Use Flyway Desktop to check and change this value if required.
      # Consider using Secure Variables for sensitive information like usernames/passwords
      TARGET_DATABASE_USERNAME : "MyUsername" # If using SQL Authentication, make sure to populate these fields!
      TARGET_DATABASE_PASSWORD : "MyPassword" # If using SQL Authentication, make sure to populate these fields!
      displayName: 'Build'
      executeBuild: true
      publishArtifacts: true
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Flyway - CLI Install ManualValidation
        if: env.FLYWAY_CLI_INSTALL_CHECK == 'true'
        run: |
          $scriptPath = "${{ GITHUB.WORKSPACE }}/scripts/Flyway_DownloadAndInstallCLI.ps1"
          if (Test-Path $scriptPath) {
            Write-Host "Script found. Running Flyway_DownloadAndInstallCLI.ps1..."
            & $scriptPath
            Write-Host "Updating PATH environment variable to include Flyway CLI Path"
              echo "C:\FlywayCLI\flyway-${{ env.FLYWAY_VERSION }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          } 
          else {
            Write-Host "Error: Script not found at path $scriptPath"
            exit 1
          }
      
      # Runs the Flyway Clean command against the Build database
      - name: Clean Build DB
        if: env.executeBuild == 'true'
        run: |
          flyway info clean info -environment="${{ env.ENVIRONMENT }}" -user="${{ env.TARGET_DATABASE_USERNAME }}" -password="${{ env.TARGET_DATABASE_PASSWORD }}" -licenseKey="${{ env.FLYWAY_LICENSE_KEY }}" -configFiles="${{ GITHUB.WORKSPACE }}\flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}\migrations" -cleanDisabled='false' "-plugins.clean.mode=all" -email="${{ env.FLYWAY_EMAIL }}" -token="${{ env.FLYWAY_TOKEN }}"
        
      # Runs the Flyway Migrate command against the Build database
      - name: Migrate Build DB
        if: env.executeBuild == 'true'
        run: |
          flyway info migrate info -environment="${{ env.ENVIRONMENT }}" -user="${{ env.TARGET_DATABASE_USERNAME }}" -password="${{ env.TARGET_DATABASE_PASSWORD }}" -licenseKey="${{ env.FLYWAY_LICENSE_KEY }}" -configFiles="${{ GITHUB.WORKSPACE }}\flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}\migrations" -cleanDisabled='false' -baselineOnMigrate="true" -email="${{ env.FLYWAY_EMAIL }}" -token="${{ env.FLYWAY_TOKEN }}"
          
      # Runs the Flyway Undo command against the Build database
      - name: undo Build DB
        if: env.executeBuild == 'true'
        run: |
          flyway info undo info -environment="${{ env.ENVIRONMENT }}" -user=${{ env.TARGET_DATABASE_USERNAME }} -password=${{ env.TARGET_DATABASE_PASSWORD }} -licenseKey="${{ env.FLYWAY_LICENSE_KEY }}" -configFiles="${{ GITHUB.WORKSPACE }}\flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}\migrations" -baselineOnMigrate="true" -cleanDisabled='false' -target="${{ env.FIRST_UNDO_SCRIPT }}" -email="${{ env.FLYWAY_EMAIL }}" -token="${{ env.FLYWAY_TOKEN }}"
 
      
      #After migration scripts are validated, publish them as an artifact
      - name: Publish Validated Migration Scripts as Artifact
        if: env.publishArtifacts == 'true'
        uses: actions/upload-artifact@v4
        with: 
          name: flyway-build-artifact-${{ github.run_number }}
          path: |
              !${{ GITHUB.WORKSPACE }}\flyway-*\**\*
              !${{ GITHUB.WORKSPACE }}\.git\**\*
              !${{ GITHUB.WORKSPACE }}\.git*\**\*
              ${{ GITHUB.WORKSPACE }}\**\schema-model\**\*
              ${{ GITHUB.WORKSPACE }}\**\migrations\**\*
              ${{ GITHUB.WORKSPACE }}\**\Scripts\**\*
              ${{ GITHUB.WORKSPACE }}\**\backups\**\*
              ${{ GITHUB.WORKSPACE }}\**\flyway.toml
              ${{ GITHUB.WORKSPACE }}\**\Filter.scpf

  test:
    name: Deploy Test
    # The type of runner that the job will run on
    runs-on: "self-hosted" # Options - self-hosted/ubuntu-latest/windows-latest (See here for more details on GitHub hosted runners - https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners)
    environment: 'test' #Ensure this environment name is setup in the projects Settings>Environment area. Ensuring any reviewers are also configFilesured 
    if: ${{ true }} #Set this variable to false to temporarily disable the job
    needs: build
    env:
      stage: 'Test'

      DATABASE_NAME: "AutoPilotTest"

      ENVIRONMENT: "Test" # This variable refers to the environment name present in the Flyway Projects TOML file. Use Flyway Desktop to check and change this value if required.
      # Consider using Secure Variables for sensitive information like usernames/passwords
      TARGET_DATABASE_USERNAME : "MyUsername" # If using SQL Authentication, make sure to populate these fields!
      TARGET_DATABASE_PASSWORD : "MyPassword" # If using SQL Authentication, make sure to populate these fields!

      CHECK_ENVIRONMENT: "Check" # This variable refers to the environment name present in the Flyway Projects TOML file. Use Flyway Desktop to check and change this value if required.
      CHECK_DATABASE_USERNAME : "MyUsername" # If using SQL Authentication, make sure to populate these fields!
      CHECK_DATABASE_PASSWORD : "MyPassword" # If using SQL Authentication, make sure to populate these fields!
      # End of Environment Secrets #
      generateDriftAndChangeReport: true
      failReleaseIfDriftDetected: false
      publishArtifacts: true
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/download-artifact@v4
        with:
          name: flyway-build-artifact-${{ github.run_number }}
      - name: Display structure of downloaded files
        run: ls -R

      - name: Flyway - CLI Install ManualValidation
        if: env.FLYWAY_CLI_INSTALL_CHECK == 'true'
        run: |
          $scriptPath = "${{ GITHUB.WORKSPACE }}/scripts/Flyway_DownloadAndInstallCLI.ps1"
          if (Test-Path $scriptPath) {
            Write-Host "Script found. Running Flyway_DownloadAndInstallCLI.ps1..."
            & $scriptPath
            Write-Host "Updating PATH environment variable to include Flyway CLI Path"
              echo "C:\FlywayCLI\flyway-${{ env.FLYWAY_VERSION }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          } 
          else {
            Write-Host "Error: Script not found at path $scriptPath"
            exit 1
          }

       # Runs the Flyway Check command, to produce a deployment report, against the Production database
      - name: Create Check Reports
        if: env.generateDriftAndChangeReport == 'true'
        run: |
          flyway check -dryrun -environment="${{ env.ENVIRONMENT }}" -user=${{ env.TARGET_DATABASE_USERNAME }} -password=${{ env.TARGET_DATABASE_PASSWORD }} -configFiles="${{ GITHUB.WORKSPACE }}\flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}\migrations" "-reportFilename=${{ GITHUB.WORKSPACE }}\reports\${{ env.DATABASE_NAME }}-Run-${{ GITHUB.RUN_ID }}-${{ env.ENVIRONMENT }}-Check-Report.html" -licenseKey="${{ env.FLYWAY_LICENSE_KEY }}" -email="${{ env.FLYWAY_EMAIL }}" -token="${{ env.FLYWAY_TOKEN }}"
        continue-on-error: true

      - name: Publish Check Report as Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: flyway-reports-test
          path: ${{ GITHUB.WORKSPACE }}\reports\**\*
        
      # Runs the Flyway Migrate against the Test database
      - name: Migrate Test DB
        if: ${{ true }}
        run: |
          flyway info migrate info -environment="${{ env.ENVIRONMENT }}" -user="${{ env.TARGET_DATABASE_USERNAME }}" -password="${{ env.TARGET_DATABASE_PASSWORD }}" -baselineOnMigrate="true" -licenseKey="${{ env.FLYWAY_LICENSE_KEY }}" -configFiles="${{ GITHUB.WORKSPACE }}\flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}\migrations" -email="${{ env.FLYWAY_EMAIL }}" -token="${{ env.FLYWAY_TOKEN }}"

  prod:
    name: Deploy Prod
    # The type of runner that the job will run on
    runs-on: "self-hosted" # Options - self-hosted/ubuntu-latest/windows-latest (See here for more details on GitHub hosted runners - https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners)
    environment: 'prod' #Ensure this environment name is setup in the projects Settings>Environment area. Ensuring any reviewers are also configFilesured 
    if: ${{ true }} #Set this variable to false to temporarily disable the job
    needs: test
    env:
      stage: 'Prod'

      DATABASE_NAME: "AutoPilotProd"

      ENVIRONMENT: "Prod"  # This variable refers to the environment name present in the Flyway Projects TOML file. Use Flyway Desktop to check and change this value if required.
      # Consider using Secure Variables for sensitive information like usernames/passwords
      TARGET_DATABASE_USERNAME : "MyUsername" # If using SQL Authentication, make sure to populate these fields!
      TARGET_DATABASE_PASSWORD : "MyPassword" # If using SQL Authentication, make sure to populate these fields!

      CHECK_ENVIRONMENT: "Check" # This variable refers to the environment name present in the Flyway Projects TOML file. Use Flyway Desktop to check and change this value if required.
      CHECK_DATABASE_USERNAME : "MyUsername" # If using SQL Authentication, make sure to populate these fields!
      CHECK_DATABASE_PASSWORD : "MyPassword" # If using SQL Authentication, make sure to populate these fields!
      # End of Environment Secrets #
      generateDriftAndChangeReport: true
      failReleaseIfDriftDetected: false
      publishArtifacts: true
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/download-artifact@v4
        with:
          name: flyway-build-artifact-${{ github.run_number }}
      - name: Display structure of downloaded files
        run: ls -R

      - name: Flyway - CLI Install ManualValidation
        if: env.FLYWAY_CLI_INSTALL_CHECK == 'true'
        run: |
          $scriptPath = "${{ GITHUB.WORKSPACE }}/scripts/Flyway_DownloadAndInstallCLI.ps1"
          if (Test-Path $scriptPath) {
            Write-Host "Script found. Running Flyway_DownloadAndInstallCLI.ps1..."
            & $scriptPath
            Write-Host "Updating PATH environment variable to include Flyway CLI Path"
              echo "C:\FlywayCLI\flyway-${{ env.FLYWAY_VERSION }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          } 
          else {
            Write-Host "Error: Script not found at path $scriptPath"
            exit 1
          }

       # Runs the Flyway Check command, to produce a deployment report, against the Production database
      - name: Create Check Reports
        if: env.generateDriftAndChangeReport == 'true'
        run: |
          flyway check -dryrun -environment="${{ env.ENVIRONMENT }}" -user=${{ env.TARGET_DATABASE_USERNAME }} -password=${{ env.TARGET_DATABASE_PASSWORD }} -configFiles="${{ GITHUB.WORKSPACE }}\flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}\migrations" "-reportFilename=${{ GITHUB.WORKSPACE }}\reports\${{ env.DATABASE_NAME }}-Run-${{ GITHUB.RUN_ID }}-${{ env.ENVIRONMENT }}-Check-Report.html" -licenseKey="${{ env.FLYWAY_LICENSE_KEY }}" -email="${{ env.FLYWAY_EMAIL }}" -token="${{ env.FLYWAY_TOKEN }}"
        continue-on-error: true

      - name: Publish Check Report as Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: flyway-reports-prod
          path: ${{ GITHUB.WORKSPACE }}\reports\**\*
        
      # Runs the Flyway Migrate against the Production database
      - name: Migrate Build DB
        if: ${{ true }}
        run: |
          flyway info migrate info -environment="${{ env.ENVIRONMENT }}" -user="${{ env.TARGET_DATABASE_USERNAME }}" -password="${{ env.TARGET_DATABASE_PASSWORD }}" -baselineOnMigrate="true" -licenseKey="${{ env.FLYWAY_LICENSE_KEY }}" -configFiles="${{ GITHUB.WORKSPACE }}\flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}\migrations" -email="${{ env.FLYWAY_EMAIL }}" -token="${{ env.FLYWAY_TOKEN }}"
